# Generated by Django 6.0.3 on 2026-03-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('daily_generate_count', models.IntegerField(default=0)),
                ('last_generate_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Party', 'Party')], max_length=50)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Lofi', 'Lofi'), ('Romantic', 'Romantic'), ('Energetic', 'Energetic')], max_length=50)),
                ('voice_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Chill', 'Chill'), ('Romantic', 'Romantic'), ('Energetic', 'Energetic')], max_length=50)),
                ('duration_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Fail', 'Fail')], default='Pending', max_length=50)),
                ('shared_link', models.URLField(blank=True, max_length=500, null=True)),
                ('story_text', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='domain.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Created success', 'Created success'), ('Created fail', 'Created fail'), ('Deleted', 'Deleted'), ('Shared', 'Shared'), ('Downloaded', 'Downloaded')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='domain.user')),
            ],
        ),
    ]
