# Generated by Django 6.0.3 on 2026-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_song_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
